# Generated by Django 5.0.4 on 2024-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(blank=True, to='post.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=64),
        ),
    ]
