# Generated by Django 5.0.4 on 2024-05-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_image'),
        ('post', '0004_alter_post_category_id_delete_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_images', to='misc.image'),
        ),
    ]
