# Generated by Django 5.0.4 on 2024-05-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_image'),
        ('post', '0006_remove_post_post_image_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ManyToManyField(blank=True, related_name='post_images', to='misc.image'),
        ),
    ]
