# Generated by Django 5.0.4 on 2024-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('event_categories', models.ManyToManyField(to='post.category')),
                ('event_tags', models.ManyToManyField(to='post.tag')),
            ],
        ),
    ]
