# Generated by Django 5.0.4 on 2024-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('post', '0002_alter_category_category_name_alter_post_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_categories',
            field=models.ManyToManyField(blank=True, to='post.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_tags',
            field=models.ManyToManyField(blank=True, to='post.tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
