# Generated by Django 5.0.4 on 2024-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_user_id'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_categories',
            field=models.ManyToManyField(blank=True, to='misc.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_tags',
            field=models.ManyToManyField(blank=True, to='misc.tag'),
        ),
    ]
