# Generated by Django 5.0.4 on 2024-05-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_event_categories_alter_event_event_tags'),
        ('misc', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_images', to='misc.image'),
        ),
    ]
